"""Core AFQMC utilities: typing, validation, overlap helpers, and IO."""

from __future__ import annotations

from typing import Any, Dict, Mapping, Optional, Tuple, Union

import numpy as onp
import yaml
from jax import numpy as jnp
from jax.tree_util import tree_leaves

from ...hamiltonian import Hamiltonian, _has_spin
from ...utils import load_pickle, save_pickle

Array = jnp.ndarray
SpinWfn = Tuple[Array, Array]
Wfn = Union[Array, SpinWfn]
RuntimeState = Dict[str, Any]


def _is_det_trial(trial: Any) -> bool:
    if isinstance(trial, (tuple, list)):
        return True
    return isinstance(trial, (jnp.ndarray, onp.ndarray))


def _is_custom_trial(trial: Any) -> bool:
    return not _is_det_trial(trial)


def _require_spin_det(trial: Wfn) -> None:
    if not _has_spin(trial):
        raise ValueError(
            "AFQMC expects spin-separated (up, down) determinant trial for "
            "built-in determinant mode."
        )


def _spin_sum_rdm(rdm: Array) -> Array:
    if rdm.ndim == 3:
        return rdm[0] + rdm[1]
    if rdm.ndim == 4:
        return rdm.sum(1)
    return rdm


def gaussian_logdens(_params: Any, fields: Any) -> Array:
    """Unnormalized log-density of N(0, I) over an arbitrary pytree."""
    vals = [jnp.real(x * jnp.conj(x)).sum() for x in tree_leaves(fields)]
    return -0.5 * jnp.sum(jnp.asarray(vals))


def extract_params(payload: Any) -> Mapping[str, Any]:
    queue = [payload]
    while queue:
        node = queue.pop(0)
        if isinstance(node, Mapping):
            if "params" in node:
                return node
            queue.extend(node.values())
            continue

        if isinstance(node, (tuple, list)):
            if len(node) == 2 and isinstance(node[1], (tuple, list)) and len(node[1]) >= 2:
                maybe_params = node[1][1]
                if isinstance(maybe_params, Mapping) and "params" in maybe_params:
                    return maybe_params
            queue.extend(node)

    raise ValueError("Cannot locate flax params in checkpoint payload.")


def normalize_ansatz_params(params: Mapping[str, Any]) -> Mapping[str, Any]:
    """Convert braket checkpoint params to ansatz.apply params if needed."""
    if not isinstance(params, Mapping) or "params" not in params:
        return params
    inner = params["params"]
    if isinstance(inner, Mapping) and "ansatz" in inner:
        return {"params": inner["ansatz"]}
    return params


def load_ansatz_cfg_from_hparams(hparams_path: str) -> Mapping[str, Any]:
    """Load ``ansatz`` mapping from a training ``hparams.yml`` file."""
    with open(hparams_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not isinstance(data, Mapping):
        raise ValueError(f"Expected mapping in {hparams_path}, got {type(data).__name__}.")

    ansatz_cfg = data.get("ansatz")
    if ansatz_cfg is None and isinstance(data.get("cfg"), Mapping):
        ansatz_cfg = data["cfg"].get("ansatz")
    if not isinstance(ansatz_cfg, Mapping):
        raise ValueError(
            f"Cannot find mapping key 'ansatz' in {hparams_path}. "
            "Expected training config generated by hafqmc.train*."
        )
    return ansatz_cfg


def mix_overlap_terms(
    sample_sign: Array,
    sample_logov: Array,
    sample_log_abs: Array,
    sample_phase: Array,
) -> tuple[Array, Array, Array]:
    """Combine per-sample overlaps into total sign/log-overlap/mix-weights."""
    log_terms = sample_logov + sample_log_abs
    phases = sample_sign * sample_phase

    shift = jnp.max(jnp.real(log_terms))
    scaled = phases * jnp.exp(log_terms - shift)
    total = jnp.sum(scaled)
    total_abs = jnp.abs(total)
    valid = total_abs > 0

    sign = jnp.where(valid, total / total_abs, 0.0 + 0.0j)
    logov = jnp.where(valid, shift + jnp.log(total_abs), -jnp.inf)
    weights = jnp.where(valid, scaled / total, jnp.zeros_like(scaled))
    return sign, logov, weights


def phaseless_from_ratio(ratio: Array) -> Array:
    """Apply the standard phaseless projection factor to a complex ratio."""
    theta = jnp.angle(ratio)
    fac = jnp.abs(ratio) * jnp.cos(theta)
    fac = jnp.real(fac)
    fac = jnp.where(jnp.isnan(fac), 0.0, fac)
    fac = jnp.where(fac < 0.0, 0.0, fac)
    return fac


def save_hamiltonian(hamil: Hamiltonian, path: str) -> None:
    save_pickle(path, hamil.to_tuple())


def load_hamiltonian(path: str) -> Hamiltonian:
    h1e, ceri, enuc, wfn0, aux = load_pickle(path)
    return Hamiltonian(h1e, ceri, enuc, wfn0, aux)


def build_hamiltonian_pickle(
    mf: Any,
    path: str,
    *,
    chol_cut: float = 1e-6,
    orth_ao: Optional[Any] = None,
    full_eri: bool = False,
    with_cc: bool = False,
    with_ghf: bool = False,
) -> Hamiltonian:
    hamil = Hamiltonian.from_pyscf(
        mf,
        chol_cut=chol_cut,
        orth_ao=orth_ao,
        full_eri=full_eri,
        with_cc=with_cc,
        with_ghf=with_ghf,
    )
    save_hamiltonian(hamil, path)
    return hamil


__all__ = [
    "Array",
    "RuntimeState",
    "SpinWfn",
    "Wfn",
    "_is_custom_trial",
    "_is_det_trial",
    "_require_spin_det",
    "_spin_sum_rdm",
    "build_hamiltonian_pickle",
    "extract_params",
    "gaussian_logdens",
    "load_ansatz_cfg_from_hparams",
    "load_hamiltonian",
    "mix_overlap_terms",
    "normalize_ansatz_params",
    "phaseless_from_ratio",
    "save_hamiltonian",
]
