"""VAFQMC trial adapter with tethered per-walker sampling.

Core behavior:
- Walkers are determinant states.
- Each walker owns an auxiliary-field pool of size ``n_samples``.
- Pool sampling target is conditioned on that walker's current position.
- After each AFQMC propagation step, each pool advances and contributes an
  extra hand-off phaseless correction.
"""

from __future__ import annotations

from typing import Any, Dict, Mapping, Optional, Tuple

import jax
import numpy as onp
from jax import lax, numpy as jnp
from jax.tree_util import tree_leaves, tree_map
import yaml

from ..ansatz import Ansatz
from ..hamiltonian import _has_spin, calc_rdm, calc_slov
from ..propagator import orthonormalize
from ..sampler import choose_sampler_maker, make_batched
from ..utils import load_pickle
from .afqmc_utils import _spin_sum_rdm

Array = jnp.ndarray
RuntimeState = Dict[str, Any]


def _gaussian_logdens(_params: Any, fields: Any) -> Array:
    """Unnormalized log-density of N(0, I) over an arbitrary pytree."""
    vals = [jnp.real(x * jnp.conj(x)).sum() for x in tree_leaves(fields)]
    return -0.5 * jnp.sum(jnp.asarray(vals))


def _extract_params(payload: Any) -> Mapping[str, Any]:
    """Extract flax params from checkpoint payload.

    Supports:
    - dict with key ``"params"``
    - train.py tuple checkpoints: (rng, (step, params, ...))
    - recursive fallback scan
    """
    queue = [payload]
    while queue:
        node = queue.pop(0)
        if isinstance(node, Mapping):
            if "params" in node:
                return node
            queue.extend(node.values())
            continue

        if isinstance(node, (tuple, list)):
            # First honor the known train.py tuple layout.
            if len(node) == 2 and isinstance(node[1], (tuple, list)) and len(node[1]) >= 2:
                maybe_params = node[1][1]
                if isinstance(maybe_params, Mapping) and "params" in maybe_params:
                    return maybe_params
            queue.extend(node)

    raise ValueError("Cannot locate flax params in checkpoint payload.")


def _normalize_ansatz_params(params: Mapping[str, Any]) -> Mapping[str, Any]:
    """Convert braket checkpoint params to ansatz.apply params if needed."""
    if not isinstance(params, Mapping) or "params" not in params:
        return params
    inner = params["params"]
    if isinstance(inner, Mapping) and "ansatz" in inner:
        return {"params": inner["ansatz"]}
    return params


def _mix_overlap_terms(
    sample_sign: Array,
    sample_logov: Array,
    sample_log_abs: Array,
    sample_phase: Array,
) -> tuple[Array, Array, Array]:
    """Combine per-sample overlaps into total sign/logov and normalized weights."""
    log_terms = sample_logov + sample_log_abs
    phases = sample_sign * sample_phase

    shift = jnp.max(jnp.real(log_terms))
    scaled = phases * jnp.exp(log_terms - shift)
    total = jnp.sum(scaled)
    total_abs = jnp.abs(total)
    valid = total_abs > 0

    sign = jnp.where(valid, total / total_abs, 0.0 + 0.0j)
    logov = jnp.where(valid, shift + jnp.log(total_abs), -jnp.inf)
    weights = jnp.where(valid, scaled / total, jnp.zeros_like(scaled))
    return sign, logov, weights


def _phaseless_from_ratio(ratio: Array) -> Array:
    """Apply phaseless projection factor from a complex ratio."""
    theta = jnp.angle(ratio)
    fac = jnp.abs(ratio) * jnp.cos(theta)
    fac = jnp.real(fac)
    fac = jnp.where(jnp.isnan(fac), 0.0, fac)
    fac = jnp.where(fac < 0.0, 0.0, fac)
    return fac


def load_ansatz_cfg_from_hparams(hparams_path: str) -> Mapping[str, Any]:
    """Load ``ansatz`` mapping from a training ``hparams.yml`` file."""
    with open(hparams_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not isinstance(data, Mapping):
        raise ValueError(f"Expected mapping in {hparams_path}, got {type(data).__name__}.")

    ansatz_cfg = data.get("ansatz")
    if ansatz_cfg is None and isinstance(data.get("cfg"), Mapping):
        ansatz_cfg = data["cfg"].get("ansatz")
    if not isinstance(ansatz_cfg, Mapping):
        raise ValueError(
            f"Cannot find mapping key 'ansatz' in {hparams_path}. "
            "Expected training config generated by hafqmc.train*."
        )
    return ansatz_cfg


class VAFQMCTrial:
    """Custom trial object consumed by ``hafqmc.afqmc.afqmc_energy``.

    Design layers:
    1. Construction/config: checkpoint loading and sampler setup.
    2. Runtime-state API: explicit import/export of walker-bound trial state.
    3. AFQMC hooks: overlap/local-energy/force-bias/update/reconfiguration/measurement.

    The AFQMC driver only relies on the runtime-state API + AFQMC hooks,
    so numerical kernels stay decoupled from object mutation details.
    """

    def __init__(
        self,
        ansatz: Ansatz,
        params: Mapping[str, Any],
        *,
        reference_wfn: Any,
        n_samples: int = 128,
        burn_in: int = 256,
        sampler_name: str = "hmc",
        sampler_kwargs: Optional[Mapping[str, Any]] = None,
        sampling_target: str = "walker_overlap",
        logdens_floor: float = -60.0,
        sample_update_steps: int = 1,
        init_walkers_from_trial: bool = False,
        init_walkers_burn_in: int = 0,
        max_prop: Optional[Any] = None,
        seed: int = 0,
    ) -> None:
        self.ansatz = ansatz
        self.params = params
        self.reference_wfn = tree_map(jnp.asarray, reference_wfn)
        self.nbasis = int(
            self.reference_wfn[0].shape[0] if _has_spin(self.reference_wfn) else self.reference_wfn.shape[0]
        )

        self.n_samples = int(n_samples)
        self.burn_in = int(burn_in)
        self.sample_update_steps = int(sample_update_steps)
        self.init_walkers_from_trial = bool(init_walkers_from_trial)
        self.init_walkers_burn_in = int(init_walkers_burn_in)
        self.sampling_target = str(sampling_target).lower()
        self.logdens_floor = float(logdens_floor)
        self.max_prop = max_prop
        self.seed = int(seed)

        if self.n_samples <= 0:
            raise ValueError("n_samples must be positive.")
        if self.burn_in < 0 or self.sample_update_steps < 0 or self.init_walkers_burn_in < 0:
            raise ValueError("burn-in/update steps must be non-negative.")

        self.fields_shape = self.ansatz.fields_shape(self.max_prop)
        zero_fields = tree_map(
            lambda s: jnp.zeros(tuple(onp.asarray(s).tolist())),
            self.fields_shape,
        )
        self.n_fields = int(sum(int(onp.prod(x.shape)) for x in tree_leaves(zero_fields)))

        sampler_name = sampler_name.lower()
        kwargs = dict(sampler_kwargs or {})
        if sampler_name in ("hmc", "hamiltonian", "hybrid") and not kwargs:
            kwargs = {"dt": 0.1, "length": 1.0}
        self._sampler_name = sampler_name
        self._sampler_kwargs = kwargs

        self._sampler = choose_sampler_maker(self._sampler_name)(
            self._build_logdens(),
            self.fields_shape,
            **self._sampler_kwargs,
        )
        self._pool_sampler = make_batched(self._sampler, self.n_samples, concat=False)

        # RNG streams.
        self._rng = jax.random.PRNGKey(self.seed)

        # Walker-bound tethered sampling state.
        self._n_walkers = 0
        self._bound_walkers = None
        self._pool_state = None
        self._pool_fields_tree = None
        self._pool_logsw = None
        self._pool_log_abs = None
        self._pool_phase = None
        self._pool_bra = None

        # Public flattened pool view used by AFQMC state.
        self.walker_fields = None  # (n_walkers, n_samples, n_fields_flat)

        # Lazily-compiled kernels keyed by (object-id/config) to reduce Python overhead.
        self._local_energy_fns: Dict[int, Any] = {}
        self._force_bias_fns: Dict[int, Any] = {}
        self._block_measure_fns: Dict[Tuple[int, int, int], Any] = {}

        # Mean-field shift setup keeps a deterministic reference RDM.
        self.rdm1 = jnp.real(self._collapse_rdm(calc_rdm(self.reference_wfn, self.reference_wfn)))

    @classmethod
    def from_checkpoint(
        cls,
        hamiltonian: Any,
        checkpoint_path: str,
        *,
        ansatz_cfg: Mapping[str, Any],
        n_samples: int = 20,
        burn_in: int = 1000,
        sampler_name: str = "hmc",
        sampler_kwargs: Optional[Mapping[str, Any]] = None,
        sampling_target: str = "walker_overlap",
        logdens_floor: float = -60.0,
        sample_update_steps: int = 1,
        init_walkers_from_trial: bool = False,
        init_walkers_burn_in: int = 0,
        max_prop: Optional[Any] = None,
        seed: int = 0,
    ) -> "VAFQMCTrial":
        payload = load_pickle(checkpoint_path)
        params = _normalize_ansatz_params(_extract_params(payload))
        ansatz = Ansatz.create(hamiltonian, **dict(ansatz_cfg))
        return cls(
            ansatz,
            params,
            reference_wfn=hamiltonian.wfn0,
            n_samples=n_samples,
            burn_in=burn_in,
            sampler_name=sampler_name,
            sampler_kwargs=sampler_kwargs,
            sampling_target=sampling_target,
            logdens_floor=logdens_floor,
            sample_update_steps=sample_update_steps,
            init_walkers_from_trial=init_walkers_from_trial,
            init_walkers_burn_in=init_walkers_burn_in,
            max_prop=max_prop,
            seed=seed,
        )

    @classmethod
    def from_hparams_checkpoint(
        cls,
        hamiltonian: Any,
        checkpoint_path: str,
        *,
        hparams_path: str = "hparams.yml",
        n_samples: int = 20,
        burn_in: int = 1000,
        sampler_name: str = "hmc",
        sampler_kwargs: Optional[Mapping[str, Any]] = None,
        sampling_target: str = "walker_overlap",
        logdens_floor: float = -60.0,
        sample_update_steps: int = 1,
        init_walkers_from_trial: bool = False,
        init_walkers_burn_in: int = 0,
        max_prop: Optional[Any] = None,
        seed: int = 0,
    ) -> "VAFQMCTrial":
        """Build trial by loading ``ansatz_cfg`` from ``hparams.yml``."""
        ansatz_cfg = load_ansatz_cfg_from_hparams(hparams_path)
        return cls.from_checkpoint(
            hamiltonian,
            checkpoint_path,
            ansatz_cfg=ansatz_cfg,
            n_samples=n_samples,
            burn_in=burn_in,
            sampler_name=sampler_name,
            sampler_kwargs=sampler_kwargs,
            sampling_target=sampling_target,
            logdens_floor=logdens_floor,
            sample_update_steps=sample_update_steps,
            init_walkers_from_trial=init_walkers_from_trial,
            init_walkers_burn_in=init_walkers_burn_in,
            max_prop=max_prop,
            seed=seed,
        )

    # ---------------------------------------------------------------------
    # Runtime-state utilities.
    # ---------------------------------------------------------------------
    def _pack_runtime_state(
        self,
        *,
        rng: Any,
        pool_state: Any,
        pool_fields_tree: Any,
        pool_logsw: Array,
        pool_bra: Any,
        pool_log_abs: Array,
        pool_phase: Array,
        walker_fields: Optional[Array] = None,
    ) -> RuntimeState:
        if walker_fields is None:
            walker_fields = self._fields_tree_to_flat(pool_fields_tree)
        return {
            "rng": rng,
            "pool_state": pool_state,
            "pool_fields_tree": pool_fields_tree,
            "pool_logsw": pool_logsw,
            "pool_bra": pool_bra,
            "pool_log_abs": pool_log_abs,
            "pool_phase": pool_phase,
            "walker_fields": walker_fields,
        }

    def _require_runtime_state(self, walkers: Any) -> RuntimeState:
        self._ensure_bound_pool(walkers)
        runtime_state = self.export_runtime_state()
        if runtime_state is None:
            raise ValueError("trial runtime_state is not initialized.")
        return runtime_state

    def _overlap_bundle_from_state(
        self,
        walkers: Any,
        runtime_state: RuntimeState,
    ) -> tuple[Array, Array, Array]:
        return self._calc_overlap_bundle_from_cache(
            walkers,
            runtime_state["pool_bra"],
            runtime_state["pool_log_abs"],
            runtime_state["pool_phase"],
        )

    def _cache_from_samples(self, fields: Any, logsw: Array) -> tuple[Any, Array, Array]:
        bra, logcoef = self._evaluate_pool_bra(fields, logsw)
        return bra, jnp.real(logcoef), jnp.exp(1.0j * jnp.imag(logcoef))

    # ---------------------------------------------------------------------
    # Runtime state I/O for AFQMC driver.
    # ---------------------------------------------------------------------
    def export_runtime_state(self) -> Optional[RuntimeState]:
        if self._pool_state is None or self._pool_logsw is None:
            return None
        return self._pack_runtime_state(
            rng=self._rng,
            pool_state=self._pool_state,
            pool_fields_tree=self._pool_fields_tree,
            pool_logsw=self._pool_logsw,
            pool_bra=self._pool_bra,
            pool_log_abs=self._pool_log_abs,
            pool_phase=self._pool_phase,
            walker_fields=self.walker_fields,
        )

    def import_runtime_state(self, runtime_state: Optional[RuntimeState]) -> None:
        if runtime_state is None:
            return
        self._rng = runtime_state["rng"]
        self._pool_state = runtime_state["pool_state"]
        self._pool_fields_tree = runtime_state["pool_fields_tree"]
        self._pool_logsw = runtime_state["pool_logsw"]
        self._pool_bra = runtime_state["pool_bra"]
        self._pool_log_abs = runtime_state["pool_log_abs"]
        self._pool_phase = runtime_state["pool_phase"]
        self.walker_fields = runtime_state["walker_fields"]
        self._n_walkers = int(self._pool_logsw.shape[0])

    def init_runtime_state(
        self,
        walkers: Any,
        *,
        key: Optional[Array] = None,
        seed: Optional[int] = None,
        burn_in: Optional[int] = None,
        reinit: bool = True,
    ) -> RuntimeState:
        self.bind_walkers(
            walkers,
            key=key,
            seed=seed,
            burn_in=burn_in,
            reinit=reinit,
        )
        state = self.export_runtime_state()
        if state is None:
            raise ValueError("Failed to initialize runtime_state.")
        return state

    def on_walkers_updated_state(
        self,
        walkers: Any,
        runtime_state: Optional[RuntimeState],
    ) -> RuntimeState:
        walkers = tree_map(jnp.asarray, walkers)
        nw = int(tree_leaves(walkers)[0].shape[0])
        if runtime_state is None:
            return self.init_runtime_state(walkers, reinit=True)
        if int(runtime_state["pool_logsw"].shape[0]) != nw:
            return self.init_runtime_state(walkers, reinit=True)
        return runtime_state

    # ---------------------------------------------------------------------
    # Trial interface used by AFQMC.
    # ---------------------------------------------------------------------
    def get_rdm1(self) -> Array:
        return self.rdm1

    def init_walkers(self, n_walkers: int, key: Array, noise: float = 0.0) -> Any:
        if self.init_walkers_from_trial:
            walkers = self._sample_walkers_from_trial(n_walkers, key)
        else:
            if not _has_spin(self.reference_wfn):
                raise ValueError("VAFQMCTrial requires spin-separated reference_wfn for AFQMC walkers.")
            w_up, w_dn = self.reference_wfn
            w_up = jnp.broadcast_to(w_up, (n_walkers,) + w_up.shape)
            w_dn = jnp.broadcast_to(w_dn, (n_walkers,) + w_dn.shape)
            walkers = (w_up, w_dn)

        if noise > 0.0:
            key, k1, k2 = jax.random.split(key, 3)
            w_up, w_dn = walkers
            w_up = w_up + noise * jax.random.normal(k1, w_up.shape)
            w_dn = w_dn + noise * jax.random.normal(k2, w_dn.shape)
            walkers = (w_up, w_dn)

        walkers, _ = orthonormalize(walkers)
        return walkers

    def orthonormalize_walkers(self, walkers: Any) -> Any:
        walkers, _ = orthonormalize(walkers)
        return walkers

    def on_walkers_updated(self, walkers: Any) -> None:
        walkers = tree_map(jnp.asarray, walkers)
        nw = int(tree_leaves(walkers)[0].shape[0])
        if nw != self._n_walkers or self._pool_state is None:
            self.bind_walkers(walkers, reinit=True)
        else:
            self._bound_walkers = walkers

    def bind_walkers(
        self,
        walkers: Any,
        *,
        key: Optional[Array] = None,
        seed: Optional[int] = None,
        burn_in: Optional[int] = None,
        reinit: bool = True,
    ) -> None:
        walkers = tree_map(jnp.asarray, walkers)
        n_walkers = int(tree_leaves(walkers)[0].shape[0])
        if n_walkers <= 0:
            raise ValueError("walkers must have positive leading batch dimension.")

        if seed is not None:
            self._rng = jax.random.PRNGKey(int(seed))
        if key is not None:
            self._rng = key

        requested_burn = self.burn_in if burn_in is None else int(burn_in)
        if requested_burn < 0:
            raise ValueError("burn_in must be non-negative.")

        need_init = (
            bool(reinit)
            or self._pool_state is None
            or self._pool_logsw is None
            or self._n_walkers != n_walkers
            or int(self._pool_logsw.shape[1]) != self.n_samples
        )
        if need_init:
            self._pool_state = self._init_pool_state(walkers, requested_burn)

        self._n_walkers = n_walkers
        self._bound_walkers = walkers
        self._pool_state, (fields, logsw) = self._sample_pool_step(walkers, self._pool_state)
        self._update_pool_cache(fields, logsw)

    def calc_slov(self, walkers: Any) -> tuple[Array, Array]:
        return self.calc_slov_state(walkers, self._require_runtime_state(walkers))

    def calc_slov_state(
        self,
        walkers: Any,
        runtime_state: RuntimeState,
    ) -> tuple[Array, Array]:
        walkers = tree_map(jnp.asarray, walkers)
        sign, logov, _ = self._overlap_bundle_from_state(walkers, runtime_state)
        return sign, logov

    def calc_local_energy(self, hamil: Any, walkers: Any) -> Array:
        return self.calc_local_energy_state(hamil, walkers, self._require_runtime_state(walkers))

    def calc_local_energy_state(
        self,
        hamil: Any,
        walkers: Any,
        runtime_state: RuntimeState,
    ) -> Array:
        walkers = tree_map(jnp.asarray, walkers)
        _, _, mix_weights = self._overlap_bundle_from_state(walkers, runtime_state)
        fn = self._get_local_energy_fn(hamil)
        return fn(walkers, runtime_state["pool_bra"], mix_weights)

    def calc_force_bias(self, _hamil: Any, walkers: Any, prop_data: Any) -> Array:
        return self.calc_force_bias_state(walkers, prop_data, self._require_runtime_state(walkers))

    def calc_force_bias_state(
        self,
        walkers: Any,
        prop_data: Any,
        runtime_state: RuntimeState,
    ) -> Array:
        walkers = tree_map(jnp.asarray, walkers)
        _, _, mix_weights = self._overlap_bundle_from_state(walkers, runtime_state)
        fn = self._get_force_bias_fn(prop_data)
        return fn(walkers, runtime_state["pool_bra"], mix_weights)

    def update_tethered_samples(
        self,
        walkers: Any,
        *,
        n_steps: Optional[int] = None,
        old_sign: Optional[Array] = None,
        old_logov: Optional[Array] = None,
    ) -> tuple[Array, Array, Array]:
        """Advance each walker's pool and return hand-off correction."""
        runtime_state = self._require_runtime_state(walkers)
        runtime_state, handoff, new_sign, new_logov = self.update_tethered_samples_state(
            walkers,
            runtime_state,
            n_steps=n_steps,
            old_sign=old_sign,
            old_logov=old_logov,
        )
        self.import_runtime_state(runtime_state)
        self._bound_walkers = tree_map(jnp.asarray, walkers)
        return handoff, new_sign, new_logov

    def update_tethered_samples_state(
        self,
        walkers: Any,
        runtime_state: RuntimeState,
        *,
        n_steps: Optional[int] = None,
        old_sign: Optional[Array] = None,
        old_logov: Optional[Array] = None,
    ) -> tuple[RuntimeState, Array, Array, Array]:
        walkers = tree_map(jnp.asarray, walkers)
        if (old_sign is None) or (old_logov is None):
            old_sign, old_logov, _ = self._overlap_bundle_from_state(walkers, runtime_state)
        else:
            old_sign = jnp.asarray(old_sign)
            old_logov = jnp.asarray(old_logov)

        steps = self.sample_update_steps if n_steps is None else int(n_steps)
        if steps < 0:
            raise ValueError("n_steps must be non-negative.")
        if steps == 0:
            ones = jnp.ones((int(tree_leaves(walkers)[0].shape[0]),), dtype=jnp.float64)
            return runtime_state, ones, old_sign, old_logov

        n_walkers = int(tree_leaves(walkers)[0].shape[0])
        sample_one = lambda key, walker, st: self._pool_sampler.sample(key, (self.params, walker), st)

        def step_body(_i, carry):
            rng, st, f, lsw = carry
            rng, sample_key = jax.random.split(rng)
            keys = jax.random.split(sample_key, n_walkers)
            st, (f, lsw) = jax.vmap(sample_one)(keys, walkers, st)
            return (rng, st, f, lsw)

        rng, state_new, fields_new, logsw_new = lax.fori_loop(
            0,
            steps,
            step_body,
            (
                runtime_state["rng"],
                runtime_state["pool_state"],
                runtime_state["pool_fields_tree"],
                runtime_state["pool_logsw"],
            ),
        )
        bra_new, log_abs_new, phase_new = self._cache_from_samples(fields_new, logsw_new)
        new_sign, new_logov, _ = self._calc_overlap_bundle_from_cache(walkers, bra_new, log_abs_new, phase_new)
        valid = jnp.isfinite(old_logov) & jnp.isfinite(new_logov) & (jnp.abs(old_sign) > 0)
        log_ratio = jnp.where(valid, new_logov - old_logov, -jnp.inf)
        sign_ratio = jnp.where(valid, new_sign / old_sign, 0.0 + 0.0j)
        handoff = _phaseless_from_ratio(sign_ratio * jnp.exp(log_ratio))

        runtime_state_new = self._pack_runtime_state(
            rng=rng,
            pool_state=state_new,
            pool_fields_tree=fields_new,
            pool_logsw=logsw_new,
            pool_bra=bra_new,
            pool_log_abs=log_abs_new,
            pool_phase=phase_new,
        )
        return runtime_state_new, handoff, new_sign, new_logov

    def stochastic_reconfiguration(self, walkers: Any, weights: Array, key: Array):
        """Resample walkers and clone their tethered pools consistently."""
        runtime_state = self._require_runtime_state(walkers)
        walkers_new, new_weights, runtime_state = self.stochastic_reconfiguration_state(
            walkers,
            weights,
            key,
            runtime_state,
        )
        self.import_runtime_state(runtime_state)
        self._bound_walkers = walkers_new
        return walkers_new, new_weights

    def stochastic_reconfiguration_state(
        self,
        walkers: Any,
        weights: Array,
        key: Array,
        runtime_state: RuntimeState,
    ) -> tuple[Any, Array, RuntimeState]:
        n_walkers = int(weights.shape[0])

        pos_weights = jnp.maximum(weights, 0.0)
        wsum = jnp.maximum(jnp.sum(pos_weights), 1.0e-12)
        probs = pos_weights / wsum
        cdf = jnp.cumsum(probs)
        u0 = jax.random.uniform(key, ())
        positions = (u0 + jnp.arange(n_walkers)) / n_walkers
        idx = jnp.searchsorted(cdf, positions)
        idx = jnp.clip(idx, 0, n_walkers - 1)

        walkers_new = tree_map(lambda x: x[idx], walkers)
        runtime_state_new = self._pack_runtime_state(
            rng=runtime_state["rng"],
            pool_state=tree_map(lambda x: x[idx], runtime_state["pool_state"]),
            pool_fields_tree=tree_map(lambda x: x[idx], runtime_state["pool_fields_tree"]),
            pool_logsw=runtime_state["pool_logsw"][idx],
            pool_bra=tree_map(lambda x: x[idx], runtime_state["pool_bra"]),
            pool_log_abs=runtime_state["pool_log_abs"][idx],
            pool_phase=runtime_state["pool_phase"][idx],
            walker_fields=runtime_state["walker_fields"][idx],
        )

        new_weights = jnp.ones_like(weights) * (wsum / n_walkers)
        return walkers_new, new_weights, runtime_state_new

    def measure_block_energy(
        self,
        hamil: Any,
        walkers: Any,
        weights: Array,
        e_estimate: Array,
        dt: float,
        n_meas: int,
    ) -> tuple[Array, Array, Array]:
        """Average n_meas trial-resampled mixed measurements with fixed walkers."""
        runtime_state = self._require_runtime_state(walkers)
        runtime_state, e_blk, sign_last, logov_last = self.measure_block_energy_state(
            hamil,
            walkers,
            weights,
            e_estimate,
            dt,
            n_meas,
            runtime_state,
        )
        self.import_runtime_state(runtime_state)
        self._bound_walkers = tree_map(jnp.asarray, walkers)
        return e_blk, sign_last, logov_last

    def measure_block_energy_state(
        self,
        hamil: Any,
        walkers: Any,
        weights: Array,
        e_estimate: Array,
        dt: float,
        n_meas: int,
        runtime_state: RuntimeState,
    ) -> tuple[RuntimeState, Array, Array, Array]:
        walkers = tree_map(jnp.asarray, walkers)
        n_meas_i = max(int(n_meas), 1)
        steps = max(int(self.sample_update_steps), 0)
        key = (id(hamil), steps, n_meas_i)
        fn = self._block_measure_fns.get(key)

        if fn is None:
            n_walkers = int(tree_leaves(walkers)[0].shape[0])
            one_walker_eloc = lambda walker, bra_samples, mweights: jnp.einsum(
                "s,s->",
                mweights,
                jax.vmap(lambda bra: hamil.local_energy(bra, walker))(bra_samples),
            )

            def measure_fn(rng, st, fields, logsw, bra0, log_abs0, phase0, walkers_in, weights_in, e_est, dt_in):
                def advance_steps(rng_in, st_in, fields_in, logsw_in):
                    if steps == 0:
                        return rng_in, st_in, fields_in, logsw_in

                    sample_one = lambda k, walker, st_: self._pool_sampler.sample(k, (self.params, walker), st_)

                    def step_body(_i, carry):
                        rng_c, st_c, f_c, lsw_c = carry
                        rng_c, sample_key = jax.random.split(rng_c)
                        keys = jax.random.split(sample_key, n_walkers)
                        st_c, (f_c, lsw_c) = jax.vmap(sample_one)(keys, walkers_in, st_c)
                        return (rng_c, st_c, f_c, lsw_c)

                    return lax.fori_loop(
                        0,
                        steps,
                        step_body,
                        (rng_in, st_in, fields_in, logsw_in),
                    )

                sign0, logov0, _ = self._calc_overlap_bundle_from_cache(
                    walkers_in, bra0, log_abs0, phase0
                )
                clip = jnp.sqrt(2.0 / dt_in)

                def meas_body(_i, carry):
                    rng_c, st_c, f_c, lsw_c, e_acc, sign_last, logov_last = carry
                    rng_c, st_c, f_c, lsw_c = advance_steps(rng_c, st_c, f_c, lsw_c)

                    bra_c, logcoef_c = self._evaluate_pool_bra(f_c, lsw_c)
                    log_abs_c = jnp.real(logcoef_c)
                    phase_c = jnp.exp(1.0j * jnp.imag(logcoef_c))
                    sign_c, logov_c, mix_weights_c = self._calc_overlap_bundle_from_cache(
                        walkers_in, bra_c, log_abs_c, phase_c
                    )

                    e_loc = jax.vmap(one_walker_eloc)(walkers_in, bra_c, mix_weights_c)
                    e_loc = jnp.real(e_loc)
                    e_loc = jnp.where(
                        jnp.abs(e_loc - e_est) > clip, e_est, e_loc
                    )
                    wsum = jnp.maximum(jnp.sum(weights_in), 1.0e-12)
                    e_blk = jnp.sum(weights_in * e_loc) / wsum
                    return (rng_c, st_c, f_c, lsw_c, e_acc + e_blk, sign_c, logov_c)

                return lax.fori_loop(
                    0,
                    n_meas_i,
                    meas_body,
                    (
                        rng,
                        st,
                        fields,
                        logsw,
                        jnp.array(0.0, dtype=jnp.float64),
                        sign0,
                        logov0,
                    ),
                )

            fn = jax.jit(measure_fn)
            self._block_measure_fns[key] = fn

        rng_new, st_new, fields_new, logsw_new, e_acc, sign_last, logov_last = fn(
            runtime_state["rng"],
            runtime_state["pool_state"],
            runtime_state["pool_fields_tree"],
            runtime_state["pool_logsw"],
            runtime_state["pool_bra"],
            runtime_state["pool_log_abs"],
            runtime_state["pool_phase"],
            walkers,
            weights,
            e_estimate,
            jnp.asarray(dt),
        )
        bra_new, log_abs_new, phase_new = self._cache_from_samples(fields_new, logsw_new)
        runtime_state_new = self._pack_runtime_state(
            rng=rng_new,
            pool_state=st_new,
            pool_fields_tree=fields_new,
            pool_logsw=logsw_new,
            pool_bra=bra_new,
            pool_log_abs=log_abs_new,
            pool_phase=phase_new,
        )
        return runtime_state_new, e_acc / float(n_meas_i), sign_last, logov_last

    # ---------------------------------------------------------------------
    # Internal helpers.
    # ---------------------------------------------------------------------
    def _build_logdens(self):
        if self.sampling_target in ("gaussian", "normal", "std"):
            return _gaussian_logdens

        if self.sampling_target in ("coeff_overlap", "reference_overlap"):
            def _logdens(params: Any, fields: Any) -> Array:
                ansatz_params = params[0] if isinstance(params, (tuple, list)) else params
                bra, bra_lw = self.ansatz.apply(ansatz_params, fields)
                _, logov = calc_slov(bra, self.reference_wfn)
                logd = jnp.real(logov + bra_lw)
                return jnp.where(jnp.isfinite(logd), logd, self.logdens_floor)

            return _logdens

        def _logdens(params: Any, fields: Any) -> Array:
            # expected params: (ansatz_params, walker)
            if isinstance(params, (tuple, list)) and len(params) == 2:
                ansatz_params, walker = params
            else:
                ansatz_params, walker = params, self.reference_wfn
            bra, bra_lw = self.ansatz.apply(ansatz_params, fields)
            _, logov = calc_slov(bra, walker)
            logd = jnp.real(logov + bra_lw)
            return jnp.where(jnp.isfinite(logd), logd, self.logdens_floor)

        return _logdens

    def _collapse_rdm(self, rdm: Array) -> Array:
        if rdm.ndim == 2 and rdm.shape[-1] == 2 * self.nbasis:
            blk = rdm.reshape(2, self.nbasis, 2, self.nbasis).swapaxes(1, 2)
            return blk[0, 0] + blk[1, 1]
        return _spin_sum_rdm(rdm)

    def _fields_to_flat(self, fields: Any) -> Array:
        return jnp.concatenate([jnp.ravel(x) for x in tree_leaves(fields)], axis=0)

    def _fields_tree_to_flat(self, fields_tree: Any) -> Array:
        return jax.vmap(jax.vmap(self._fields_to_flat))(fields_tree)

    def _sample_walkers_from_trial(self, n_walkers: int, key: Array) -> Any:
        """Initialize walkers by sampling ansatz outputs from trial distribution."""
        walker_sampler = make_batched(self._sampler, n_walkers, concat=False)
        sampler_params = (self.params, self.reference_wfn)

        key, init_key = jax.random.split(key)
        state = walker_sampler.init(init_key, sampler_params)
        if self.init_walkers_burn_in > 0:
            key, burn_key = jax.random.split(key)
            state = walker_sampler.burn_in(
                burn_key,
                sampler_params,
                state,
                self.init_walkers_burn_in,
            )
        key, sample_key = jax.random.split(key)
        _, (fields, _logsw) = walker_sampler.sample(sample_key, sampler_params, state)
        walkers, _ = jax.vmap(lambda f: self.ansatz.apply(self.params, f))(fields)
        if not _has_spin(walkers):
            raise ValueError("init_walkers_from_trial requires spin-separated ansatz output.")
        return walkers

    def _evaluate_pool_bra(self, fields: Any, logsw: Array) -> tuple[Any, Array]:
        eval_ansatz = jax.vmap(jax.vmap(lambda f: self.ansatz.apply(self.params, f)))
        bra_samples, bra_logw = eval_ansatz(fields)
        return bra_samples, (bra_logw - logsw)

    def _update_pool_cache(self, fields: Any, logsw: Array) -> None:
        self._pool_fields_tree = fields
        self._pool_logsw = logsw
        self._pool_bra, logcoef = self._evaluate_pool_bra(fields, logsw)
        self._pool_log_abs = jnp.real(logcoef)
        self._pool_phase = jnp.exp(1.0j * jnp.imag(logcoef))
        self.walker_fields = self._fields_tree_to_flat(fields)

    def _init_pool_state(self, walkers: Any, burn_steps: int):
        self._rng, init_key = jax.random.split(self._rng)
        init_keys = jax.random.split(init_key, int(tree_leaves(walkers)[0].shape[0]))
        state = jax.vmap(lambda k, w: self._pool_sampler.init(k, (self.params, w)))(init_keys, walkers)

        if burn_steps > 0:
            self._rng, burn_key = jax.random.split(self._rng)
            burn_keys = jax.random.split(burn_key, int(tree_leaves(walkers)[0].shape[0]))
            state = jax.vmap(
                lambda k, w, st: self._pool_sampler.burn_in(k, (self.params, w), st, burn_steps)
            )(burn_keys, walkers, state)
        return state

    def _sample_pool_step(self, walkers: Any, state: Any):
        self._rng, sample_key = jax.random.split(self._rng)
        keys = jax.random.split(sample_key, self._n_walkers)
        sample_one = lambda key, walker, st: self._pool_sampler.sample(key, (self.params, walker), st)
        return jax.vmap(sample_one)(keys, walkers, state)

    def _ensure_bound_pool(self, walkers: Any) -> None:
        walkers = tree_map(jnp.asarray, walkers)
        nw = int(tree_leaves(walkers)[0].shape[0])
        bad = (
            self._pool_state is None
            or self._pool_logsw is None
            or self._n_walkers != nw
            or int(self._pool_logsw.shape[1]) != self.n_samples
        )
        if bad:
            self.bind_walkers(walkers, reinit=True)
        else:
            self._bound_walkers = walkers

    def _calc_overlap_bundle_from_cache(
        self,
        walkers: Any,
        pool_bra: Any,
        pool_log_abs: Array,
        pool_phase: Array,
    ) -> tuple[Array, Array, Array]:
        def one_walker(walker, bra_samples, log_abs, phase):
            sample_sign, sample_logov = jax.vmap(lambda bra: calc_slov(bra, walker))(bra_samples)
            return _mix_overlap_terms(sample_sign, sample_logov, log_abs, phase)

        return jax.vmap(one_walker)(
            walkers,
            pool_bra,
            pool_log_abs,
            pool_phase,
        )

    def _get_local_energy_fn(self, hamil: Any):
        key = id(hamil)
        fn = self._local_energy_fns.get(key)
        if fn is None:
            def local_energy_fn(walkers, pool_bra, mix_weights):
                def one_walker(walker, bra_samples, weights):
                    es = jax.vmap(lambda bra: hamil.local_energy(bra, walker))(bra_samples)
                    return jnp.einsum("s,s->", weights, es)

                return jax.vmap(one_walker)(walkers, pool_bra, mix_weights)

            fn = jax.jit(local_energy_fn)
            self._local_energy_fns[key] = fn
        return fn

    def _get_force_bias_fn(self, prop_data: Any):
        key = id(prop_data)
        fn = self._force_bias_fns.get(key)
        if fn is None:
            def force_bias_fn(walkers, pool_bra, mix_weights):
                def one_walker(walker, bra_samples, weights):
                    rdms = jax.vmap(lambda bra: self._collapse_rdm(calc_rdm(bra, walker)))(bra_samples)
                    rdm_mix = jnp.einsum("s,spq->pq", weights, rdms)
                    return jnp.einsum("kpq,pq->k", prop_data.vhs, rdm_mix)

                return jax.vmap(one_walker)(walkers, pool_bra, mix_weights)

            fn = jax.jit(force_bias_fn)
            self._force_bias_fns[key] = fn
        return fn
